spring.application.name=super-usuario

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5333/post_super
spring.datasource.username=paiperrie
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true